# **Introduction to Data Aggregation for Business Intelligence**

**Aggregation** refers to the process of summarizing data by applying functions to groups of data.  

Suppose we have a DataFrame `sales_data` containing information about sales for different regions:

| Region | Sales |
|--------|-------|
| East   | 100   |
| West   | 150   |
| East   | 200   |
| West   | 120   |
| North  | 180   |

We want to calculate the total sales for each region.

1. **Grouping Data**:
   We start by grouping the data by the 'Region' column:


   
   | Region | Sales |
   |--------|-------|
   | East   | 100   |
   | East   | 200   |
   | West   | 150   |
   | West   | 120   |
   | North  | 180   |


   
2. **Applying Aggregation Function**:
   Next, we apply the sum() function to calculate the total sales for each region:
   

   | Region | Total Sales |
   |--------|-------------|
   | East   | 300         |
   | West   | 270         |
   | North  | 180         |



3. **Viewing Results**:
   Finally, we view the aggregated results, which show the total sales for each region.



## **The Essence of Data Aggregation**
Data aggregation is a cornerstone process in Business Intelligence (BI) that involves compiling and summarizing detailed data to form a condensed and insightful view. This process is similar to distilling vast volumes of information to extract the essence, providing a clear and comprehensive understanding of underlying trends, patterns, and anomalies within the business context.

## Significance in Business Intelligence
In the realm of BI, where strategic decisions are driven by data, the role of data aggregation cannot be overstated. It **transforms raw**, often chaotic data into structured, meaningful information, enabling businesses to:
- **Enhance Decision-Making:** Aggregated data provides a macro-level view of business metrics, making it easier for executives and managers to make informed decisions without being bogged down by the complexities of raw data.
- **Improve Efficiency:** By summarizing data, aggregation reduces the volume of information to be processed and analyzed, leading to quicker insights and more efficient data handling.
- **Enable Effective Reporting:** Aggregated data forms the foundation of BI reporting and dashboards, presenting key metrics in an accessible format that can be easily interpreted by stakeholders across the organization.

## Applications in BI
Data aggregation finds its application across various facets of BI, including:
- **Trend Analysis:** Summarizing sales data over time to identify growth trends, seasonal patterns, or potential market shifts.
- **Performance Metrics:** Aggregating financial and operational data to assess the performance of different business units, products, or services.
- **Customer Insights:** Compiling customer interaction and transaction data to understand customer behavior, preferences, and satisfaction levels.

# **Mastering GroupBy in Pandas**

## Introduction to Data Grouping
- Data grouping is a fundamental aspect of data analysis that allows for organizing and summarizing large datasets into meaningful categories.
- This process is essential in extracting valuable insights from data by enabling analysts to perform operations on subsets of data grouped according to certain criteria.

### Definition and Importance of Data Grouping in Analysis
- Data grouping involves categorizing data into segments based on shared attributes, which can then be analyzed independently.
- This approach simplifies complex datasets, making it easier to identify patterns, trends, and anomalies.
- In the context of **Business Intelligence (BI)**, data grouping is instrumental in breaking down business **metrics** by categories such as **time periods**, **geographic regions**, **product lines**, or **customer demographics**, thereby facilitating targeted analysis and strategic decision-making.

### Overview of the GroupBy Operation
- The groupby operation is a powerful tool in data analysis, particularly in the Pandas library for Python.
- It implements the "split-apply-combine" paradigm where data is first split into groups based on one or more keys, an operation is applied to each group independently, and the results are combined back into a structured form.
- This operation is versatile and can be used for a wide range of data manipulation tasks, from simple aggregations to complex transformations and filtrations.

## GroupBy: Split, Apply, Combine

The name `Group by` comes from a command in the SQL database language, but in Pandas you could thing of it in term of  _`split, apply, combine`_. The idea is to apply the same function on subsets of your dataframe, based on some key to split the dataframe in subsets.

The **GroupBy** operation involves the following steps:
- **Splitting** the data into groups based on some criteria
- **Applying** a function to each group independently
- **Combining** the results into a data structure

![image.png]()

In [ ]:
# Recreate the DataFrame based on the visual
import pandas as pd
df = pd.DataFrame({
    'key': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'],
    'data': [0, 5, 10, 5, 10, 15, 10, 15, 20]
})

In [ ]:
df

  key  data
0   A     0
1   B     5
2   C    10
3   A     5
4   B    10
5   C    15
6   A    10
7   B    15
8   C    20

**1. Split**

The first step in the process is to "split" the data. This involves dividing the data into groups based on some key(s). In our example, we are splitting the data based on the 'key' column, which contains categorical variables 'A', 'B', and 'C'.

In [ ]:
grouped = df.groupby('key')

In [ ]:
grouped

In this code, `groupby('key') `is used to create a GroupBy object. It doesn't actually compute anything until we apply a function. However, it has separated our DataFrame into three groups, one for each unique value in the 'key' column.

**2. Apply**

After splitting the data into groups, the next step is to "apply" a function to each group independently. This could be an aggregation, transformation, or filtration function.

In [ ]:
grouped.sum()

     data
key
A      15
B      30
C      45

Here, we apply the sum() function to the 'data' column of each group. The sum() function is one of several built-in aggregate functions that Pandas can apply to groups.

**3. Combine**

The final step is to "combine" the results of the function back into a single DataFrame. When an aggregation function is applied, Pandas does this automatically.

In [ ]:
df.groupby('key').sum()

     data
key
A      15
B      30
C      45

This strategy is elegant and powerful, especially when dealing with larger datasets, as it allows for complex operations to be performed on different subsets of data in a concise and readable manner. It's also a testament to the elegant of Pandas, which enables such operations with minimal code.

# Grouping Data in Pandas

## Single Column Grouping

Grouping by a single column is straightforward in Pandas. You select the column you want to group by, and Pandas will create a GroupBy object which can be used to apply aggregate, transformation, or filter operations.

### Syntax and Basic Usage

The syntax for grouping by a single column in Pandas is:

```python
grouped = dataframe.groupby('column_name')

**Load Sales Data**

Let's consider a DataFrame df that records **sales data** for a retail chain. The DataFrame includes the columns: Date, Region, Product_Category, Sales, and Quantity. If we wanted to group this data by Region, we'd use the following code:

In [ ]:
sales = pd.read_csv('/content/bi_course_data_aggregation_data.csv')

In [ ]:
sales.head()

         Date Region Product_Category   Sales  Quantity
0  2022-01-01   East         Clothing  7202.0        12
1  2022-01-02   West      Electronics  7412.0         5
2  2022-01-03  North      Electronics  5420.0         5
3  2022-01-04   East        Groceries  6232.0         6
4  2022-01-05   East         Clothing  7991.0         9

**Inspecting GroupBy Objects**

Here are some ways to understand and inspect what's in a GroupBy object:

**Viewing Groups:**

The **.groups** attribute returns a dictionary where each key is a group name (the unique values from the grouping column), and each value is the index labels of the rows belonging to that group.

In [ ]:
sales.groupby('Region').groups

{'East': [0, 3, 4, 8, 10, 11, 12, 13, 19, 39, 40, 41, 47, 50, 52, 54, 58, 60, 61, 64, 78, 80, 84, 85, 100, 109, 111, 114, 123, 134, 138, 145, 146, 147, 150, 151, 153, 156, 160, 167, 168, 172, 176, 177, 179, 181, 183, 187, 188, 190, 191, 193, 194, 199, 200, 202, 210, 211, 213, 214, 219, 220, 221, 238, 241, 244, 249, 255, 256, 259, 264, 268, 269, 283, 285, 291, 297, 302, 311, 313, 314, 316, 318, 326, 327, 333, 337, 340, 342, 344, 345, 346, 349, 355, 359, 364, 365, 368, 369, 386, ...], 'North': [2, 6, 7, 15, 21, 30, 31, 35, 37, 38, 57, 59, 62, 63, 67, 72, 74, 82, 87, 99, 116, 119, 121, 124, 127, 131, 132, 133, 135, 136, 137, 139, 141, 148, 152, 154, 158, 161, 165, 171, 178, 180, 184, 185, 192, 198, 203, 205, 209, 212, 215, 217, 226, 228, 229, 243, 246, 247, 248, 251, 253, 254, 260, 262, 263, 274, 276, 278, 286, 287, 288, 290, 292, 298, 300, 301, 305, 317, 321, 330, 331, 336, 351, 352, 358, 361, 362, 374, 377, 379, 383, 384, 388, 389, 399, 403, 413, 415, 416, 425, ...], 'South': [9, 20, 22, 25, 26, 27, 33, 34, 42, 48, 49, 51, 65, 69, 70, 71, 73, 75, 86, 89, 92, 93, 94, 95, 96, 98, 101, 102, 104, 105, 106, 108, 113, 117, 122, 126, 155, 157, 164, 169, 175, 182, 186, 189, 195, 196, 208, 222, 224, 225, 227, 230, 236, 237, 240, 245, 250, 257, 261, 265, 270, 277, 279, 282, 284, 293, 294, 296, 303, 304, 307, 309, 319, 323, 324, 325, 334, 343, 356, 363, 366, 367, 372, 378, 381, 397, 406, 409, 412, 417, 419, 420, 421, 422, 431, 447, 449, 450, 451, 452, ...], 'West': [1, 5, 14, 16, 17, 18, 23, 24, 28, 29, 32, 36, 43, 44, 45, 46, 53, 55, 56, 66, 68, 76, 77, 79, 81, 83, 88, 90, 91, 97, 103, 107, 110, 112, 115, 118, 120, 125, 128, 129, 130, 140, 142, 143, 144, 149, 159, 162, 163, 166, 170, 173, 174, 197, 201, 204, 206, 207, 216, 218, 223, 231, 232, 233, 234, 235, 239, 242, 252, 258, 266, 267, 271, 272, 273, 275, 280, 281, 289, 295, 299, 306, 308, 310, 312, 315, 320, 322, 328, 329, 332, 335, 338, 339, 341, 347, 348, 350, 353, 354, ...]}

**Getting a Specific Group:**

The **.get_group()** method allows you to retrieve a group corresponding to a specific key.

In [ ]:
sales.groupby('Region').get_group('East')

           Date Region Product_Category   Sales  Quantity
0    2022-01-01   East         Clothing  7202.0        12
3    2022-01-04   East        Groceries  6232.0         6
4    2022-01-05   East         Clothing  7991.0         9
8    2022-01-09   East        Groceries  7814.0        12
10   2022-01-11   East      Electronics  5813.0        10
..          ...    ...              ...     ...       ...
472  2023-04-18   East      Electronics  2243.0         8
474  2023-04-20   East        Groceries  9603.0        15
486  2023-05-02   East        Groceries  2298.0        12
495  2023-05-11   East      Electronics  6135.0         8
496  2023-05-12   East      Electronics  3694.0        19

[122 rows x 5 columns]

**Number of Groups:**

The **.ngroups** attribute gives you the number of groups.

In [ ]:
sales.groupby('Region').ngroups

4

**Looping Over Groups:**

You can iterate over a **GroupBy** object, which returns a tuple with the group name and the data for each group.

In [ ]:
for name, group in sales.groupby('Region'):
    print(f"Region: {name}")
    print(group.head(), "\n")

Region: East
          Date Region Product_Category   Sales  Quantity
0   2022-01-01   East         Clothing  7202.0        12
3   2022-01-04   East        Groceries  6232.0         6
4   2022-01-05   East         Clothing  7991.0         9
8   2022-01-09   East        Groceries  7814.0        12
10  2022-01-11   East      Electronics  5813.0        10

Region: North
          Date Region Product_Category   Sales  Quantity
2   2022-01-03  North      Electronics  5420.0         5
6   2022-01-07  North        Groceries  1024.0        12
7   2022-01-08  North         Clothing  1681.0         3
15  2022-01-16  North         Clothing   109.0        17
21  2022-01-22  North         Clothing  1115.0         7

Region: South
          Date Region Product_Category   Sales  Quantity
9   2022-01-10  South        Furniture  3424.0        17
20  2022-01-21  South        Groceries  5224.0        13
22  2022-01-23  South        Furniture  2293.0         9
25  2022-01-26  South         Clothing  4258.0         4
26  2022-01-27  South         Clothing  4025.0        13

Region: West
          Date Region Product_Category   Sales  Quantity
1   2022-01-02   West      Electronics  7412.0         5
5   2022-01-06   West      Electronics  2879.0         2
14  2022-01-15   West        Furniture  1938.0        19
16  2022-01-17   West        Groceries  2971.0        14
17  2022-01-18   West        Furniture  9089.0         9

**Size of Each Group:**

The **.size()** method returns a Series with the size or count of each group.

In [ ]:
sales.groupby('Region').size()

Region
East     122
North    122
South    108
West     148
dtype: int64

**First and Last Entry:**

The **.first()** and **.last()** methods return the first and last row of data for each group, respectively.

In [ ]:
sales.groupby('Region').first()

              Date Product_Category   Sales  Quantity
Region
East    2022-01-01         Clothing  7202.0        12
North   2022-01-03      Electronics  5420.0         5
South   2022-01-10        Furniture  3424.0        17
West    2022-01-02      Electronics  7412.0         5

In [ ]:
sales.groupby('Region').last()

              Date Product_Category   Sales  Quantity
Region
East    2023-05-12      Electronics  3694.0        19
North   2023-05-14        Groceries  1509.0        18
South   2023-05-09        Groceries  8805.0         4
West    2023-05-15         Clothing  4941.0         6

**Sampling:**

Sometimes, you may want to take a random sample from each group.

In [ ]:
sales.groupby('Region').sample(3) # Gives 3 random samples from every region

           Date Region Product_Category   Sales  Quantity
495  2023-05-11   East      Electronics  6135.0         8
172  2022-06-22   East        Furniture  3186.0         7
190  2022-07-10   East        Furniture     NaN         5
492  2023-05-08  North        Furniture  4277.0        14
30   2022-01-31  North      Electronics  4100.0         6
358  2022-12-25  North        Furniture   927.0         4
452  2023-03-29  South      Electronics  8138.0         7
366  2023-01-02  South      Electronics  8895.0         2
309  2022-11-06  South      Electronics  2070.0        12
469  2023-04-15   West         Clothing  3775.0        18
348  2022-12-15   West         Clothing     NaN        11
88   2022-03-30   West        Groceries  5215.0        10

Understanding and utilizing these pre-aggregation methods allows you to comprehensively explore and manipulate the grouped data.

# **Applying Aggregation Functions**

After you have grouped your data and potentially performed some preliminary operations, the next step in the analysis process is to apply aggregation functions to your groups. Aggregation functions are used to compute summary statistics for each group, which can be especially insightful when analyzing grouped data.

## Common Aggregation Functions

Pandas provides a number of built-in methods for aggregation:

- `.sum()`: Computes the sum of the values for each group.
- `.mean()`: Calculates the mean of the values for each group.
- `.median()`: Finds the median of the values for each group.
- `.min()`: Determines the minimum value within each group.
- `.max()`: Identifies the maximum value within each group.
- `.count()`: Counts the number of non-null values within each group.
- `.std()`: Calculates the standard deviation of the values within each group.

## Custom Aggregations

In addition to the built-in methods, Pandas allows for custom aggregation functions using the `.agg()` method:

- `.agg()`: Can take a function, a string function name, a list of functions, or a dict mapping column names to functions. This flexibility allows you to perform multiple aggregations in a single call and apply specific functions to specific columns.

## Examples of Aggregation

Using the `grouped_by_region` object from the previous section, let's apply some of these aggregation functions.

In [ ]:
# Calculate the total sales per region
sales.groupby('Region')['Sales'].sum()

Region
East     579111.0
North    529247.0
South    536943.0
West     747092.0
Name: Sales, dtype: float64

In [ ]:
# Compute the average quantity sold per region
sales.groupby('Region')['Sales'].mean()

Region
East     4992.336207
North    4485.144068
South    5018.158879
West     5374.762590
Name: Sales, dtype: float64

In [ ]:
# Apply multiple aggregation functions to get summary statistics for sales
sales.groupby('Region')['Sales'].agg(['sum', 'mean', 'std', 'min', 'max'])

             sum         mean          std    min     max
Region
East    579111.0  4992.336207  2723.107662  105.0  9866.0
North   529247.0  4485.144068  2870.917710  109.0  9960.0
South   536943.0  5018.158879  2760.717271  194.0  9965.0
West    747092.0  5374.762590  2569.666920  154.0  9931.0

In [ ]:
# Define a custom function to calculate the range of sales
sales.groupby(['Region'])['Sales'].agg(range_sales=lambda x: x.max() - x.min())

        range_sales
Region
East         9761.0
North        9851.0
South        9771.0
West         9777.0

**Interpreting the Results**

The output from these aggregation functions provides a comprehensive view of the sales data within each region. For instance, the total and average sales can indicate regions with high or low demand, while the range of sales can suggest variability in sales within each region. Standard deviation gives insight into the sales volatility, which can be crucial for inventory and supply chain planning.

By applying these aggregation functions, you can gain a deeper understanding of the regional performance and make data-driven decisions to improve business operations. This kind of analysis is integral to Business Intelligence as it turns raw data into actionable insights.

---
# Multiple Columns Grouping in Pandas

Grouping by multiple columns in Pandas is an extension of single column grouping. It allows you to explore data with a multi-dimensional approach. When you group by more than one column, you can dissect the dataset across different categorical variables simultaneously. This multi-level grouping can provide a deeper understanding of how combinations of different factors affect your data.

## Grouping by More than One Column

When you group by multiple columns, Pandas creates a hierarchical index (or MultiIndex) for the resulting GroupBy object. This is akin to creating a pivot table where each combination of group keys forms a unique group in the resulting hierarchy.

## Syntax and Basic Usage

The syntax for multiple column grouping is similar to single column grouping but with a list of column names:

```python
grouped = dataframe.groupby(['column_1', 'column_2'])

We want to analyze sales based on both **Region** and **Product_Category**. Here's how you can group by these two dimensions:

In [ ]:
# Grouping the DataFrame by 'Region' and 'Product_Category'
sales.groupby(['Region', 'Product_Category']).size()

Region  Product_Category
East    Clothing            27
        Electronics         31
        Furniture           35
        Groceries           29
North   Clothing            24
        Electronics         32
        Furniture           32
        Groceries           34
South   Clothing            26
        Electronics         28
        Furniture           24
        Groceries           30
West    Clothing            33
        Electronics         45
        Furniture           31
        Groceries           39
dtype: int64

Now, **grouped_by_region_and_category** is a **GroupBy **object that has data grouped by unique combinations of **Region** and **Product_Category**.

In [ ]:
# Calculating total sales for each combination of 'Region' and 'Product_Category'
sales.groupby(['Region', 'Product_Category'])['Sales'].sum()

Region  Product_Category
East    Clothing            118538.0
        Electronics         132222.0
        Furniture           181749.0
        Groceries           146602.0
North   Clothing             99901.0
        Electronics         142221.0
        Furniture           129130.0
        Groceries           157995.0
South   Clothing            110901.0
        Electronics         139768.0
        Furniture           129604.0
        Groceries           156670.0
West    Clothing            155537.0
        Electronics         247141.0
        Furniture           153395.0
        Groceries           191019.0
Name: Sales, dtype: float64

In [ ]:
# Unstacking the MultiIndex to create a DataFrame
sales.groupby(['Region', 'Product_Category'])['Sales'].sum().unstack(level=['Product_Category'])

Product_Category  Clothing  Electronics  Furniture  Groceries
Region
East              118538.0     132222.0   181749.0   146602.0
North              99901.0     142221.0   129130.0   157995.0
South             110901.0     139768.0   129604.0   156670.0
West              155537.0     247141.0   153395.0   191019.0

In [ ]:
sales.head()

         Date Region Product_Category   Sales  Quantity
0  2022-01-01   East         Clothing  7202.0        12
1  2022-01-02   West      Electronics  7412.0         5
2  2022-01-03  North      Electronics  5420.0         5
3  2022-01-04   East        Groceries  6232.0         6
4  2022-01-05   East         Clothing  7991.0         9

In [ ]:
# Creating a pivot table to summarize sales

# Pivot means changing structure of rows to be columns
# Ex: Changing region to be a column and changing produc_category to be a row
sales.pivot_table(values='Quantity', index=['Product_Category'], columns='Region', aggfunc='sum')

Region            East  North  South  West
Product_Category
Clothing           266    243    254   331
Electronics        311    326    297   460
Furniture          318    373    248   302
Groceries          335    356    257   407

# **Advanced GroupBy Operations: Window Functions**

Window functions in Pandas are powerful tools for calculating aggregates over rolling or expanding windows. They are particularly useful for analyzing time-series data and deriving insights from sequential observations.

## Understanding Window Functions

Window functions operate on a set of rows and return a single value for each row, preserving the original row structure. They enable complex calculations such as moving averages, cumulative sums, or rank calculations.

## Applying Rolling and Expanding Operations

### **Rolling Operations**

Rolling operations compute statistics (e.g., sum, mean, standard deviation) over a fixed window of observations that moves along with the data. This allows for trend analysis and smoothing techniques.

In [ ]:
# Every 3 rows will be averaged
# Creates new column for Rolling_Avg_Sales
sales['Rolling_Avg_Sales'] = sales['Sales'].rolling(window=3, min_periods=1).mean()

In [ ]:
sales.head()

         Date Region Product_Category   Sales  Quantity  Rolling_Avg_Sales
0  2022-01-01   East         Clothing  7202.0        12        7202.000000
1  2022-01-02   West      Electronics  7412.0         5        7307.000000
2  2022-01-03  North      Electronics  5420.0         5        6678.000000
3  2022-01-04   East        Groceries  6232.0         6        6354.666667
4  2022-01-05   East         Clothing  7991.0         9        6547.666667

In [ ]:
sales['Expanding_Avg_Sales'] = sales['Sales'].expanding().mean()
sales.head()

# Expanding average does not specify a window size because it
# averages as you move ahead.
# While rolling specifies the number of rows to average.

,Date,Region,Product_Category,Sales,Quantity,Rolling_Avg_Sales,Expanding_Avg_Sales
0,2022-01-01,East,Clothing,7202.0,12,7202.000000,7202.0
1,2022-01-02,West,Electronics,7412.0,5,7307.000000,7307.0
2,2022-01-03,North,Electronics,5420.0,5,6678.000000,6678.0
3,2022-01-04,East,Groceries,6232.0,6,6354.666667,6566.5
4,2022-01-05,East,Clothing,7991.0,9,6547.666667,6851.4

In [ ]:
!jupyter nbconvert --to html "/content/Data_Aggregation_start_IanGabrielEusebio.ipynb"

[NbConvertApp] Converting notebook /content/Data_Aggregation_start_IanGabrielEusebio.ipynb to html
[NbConvertApp] Writing 546601 bytes to /content/Data_Aggregation_start_IanGabrielEusebio.html